export const siteSettings = {
  name: "siteSettings",
  title: "Webbplatsinnehåll (Start, Om oss, Footer)",
  type: "document",
  fields: [
    {
      name: "siteName",
      title: "Webbplatsnamn",
      type: "string",
      validation: (Rule) => Rule.required().min(2),
    },
    {
      name: "tagline",
      title: "Huvudrubrik på startsidan",
      type: "string",
      description: "Stor rubrik på startsidan.",
      validation: (Rule) => Rule.required().min(8).max(90),
    },
    {
      name: "heroText",
      title: "Introduktionstext på startsidan",
      type: "text",
      rows: 4,
      validation: (Rule) => Rule.required().min(30).max(320),
    },
    {
      name: "restaurantsPriceIntro",
      title: "Text ovanför prislista för Restauranger",
      type: "text",
      rows: 4,
      description: "Visas under rubriken Restauranger och ovanför prislistan.",
      validation: (Rule) => Rule.required().min(20),
    },
    {
      name: "restaurantsIntro",
      title: "Text under rubriken 'Våra restaurangkunder'",
      type: "text",
      rows: 4,
      description: "Visas under rubriken Våra restaurangkunder.",
      validation: (Rule) => Rule.required().min(20),
    },
    {
      name: "footerEmail",
      title: "E-post i footer",
      type: "string",
      validation: (Rule) => Rule.required().email(),
    },
    {
      name: "footerInstagramUrl",
      title: "Instagram-länk i footer",
      type: "url",
      validation: (Rule) => Rule.required().uri({ scheme: ["http", "https"] }),
    },
    {
      name: "footerLinkedinUrl",
      title: "LinkedIn-länk i footer",
      type: "url",
      validation: (Rule) => Rule.required().uri({ scheme: ["http", "https"] }),
    },
    {
      name: "aboutTitle",
      title: "Rubrik för Om oss",
      type: "string",
      validation: (Rule) => Rule.required().min(2),
    },
    {
      name: "aboutBody",
      title: "Text för Om oss",
      type: "text",
      rows: 8,
      validation: (Rule) => Rule.required().min(40),
    },
    {
      name: "aboutImage",
      title: "Bild för Om oss",
      type: "image",
      options: { hotspot: true },
    },
    {
      name: "newsletterTitle",
      title: "Rubrik i nyhetsbrevspopup",
      type: "string",
      validation: (Rule) => Rule.required().min(2),
    },
    {
      name: "newsletterText",
      title: "Text i nyhetsbrevspopup",
      type: "text",
      rows: 4,
      validation: (Rule) => Rule.required().min(20).max(220),
    },
    {
      name: "newsletterCtaLabel",
      title: "Knapptext i nyhetsbrevspopup",
      type: "string",
      validation: (Rule) => Rule.required().min(3).max(40),
    },
    {
      name: "newsletterEmbedUrl",
      title: "Mailchimp-formulärets action-URL",
      type: "url",
      description:
        "Klistra in form action-URL från Mailchimp embed-koden, till exempel https://.../subscribe/post?u=...&id=...",
      validation: (Rule) => Rule.uri({ scheme: ["http", "https"] }),
    },
  ],
};
